version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000